### ISSUE TITLE
web 파트 tslint 관련 질문있습니다.

### ISSUE THREAD

**Issue by khg0712** [iodes/TimeCat#12]
tslint모듈이 devDependency로 설정되었는데 사용되도록 설정된건가요??
@Web-Engine

**Comment by Web-Engine** [comment]
devDependency로 설정된것이 맞습니다.
tslint는 실제로 저희가 개발한 프로그램을 구동하는데 필요한 것이 아니라, 개발할 때 문법 오류를 잡아주기 위해 설치한 것 입니다.

**Comment by khg0712** [comment]
tslint를 사용할 때 tslint.json의 사용이 필요한 걸로 알고 있는데 설정이 안된 것 같아서 여쭤봤습니다.

**Comment by Web-Engine** [comment]
아 맞습니다. tslint.json 파일이 빠졌네요.
설정해서 올리도록 하겠습니다.
