### ISSUE TITLE
Idle/Active Log에 관한 질문

### ISSUE THREAD

**Issue by LiteHell** [iodes/TimeCat#43]
Idle/Active Log에서의 Application Id는 그 당시 이용하고 있던 프로그램의 Id인가요? 아니면 그냥 NULL인가요?

**Comment by SteaI** [comment]
Acitivity의 Application Id 는 해당 앱의 로그를 저장하기 때문에 NOT NULL 입니다.

**Comment by LiteHell** [comment]
알겠습니다.
