### ISSUE TITLE
SetWinEventHook 호출 쓰레드 + ManualResetEvent 관련 질문 드립니다.

### ISSUE THREAD

**Issue by Plurdis** [iodes/TimeCat#46]
개발 중 막히는 부분이 있어 질문드립니다.

[이 곳](https://github.com/iodes/TimeCat/blob/master/TimeCat.Labs/Plurdis/FunctionTest/FunctionTest/Program.cs#L22-L30)을 보시면, STA 쓰레드 내에서 User32의 SetWinEventHook을 호출하고 있고 그 아래에 ManualResetEvent 객체에서 WaitOne() 함수를 호출하고 있습니다.

이 부분을 클래스로 따로 빼서 테스트를 해보고 있는데 외부 클래스에서 쓰레드를 STA 쓰레드로 만들고 해당 SetWinEventHook을 호출해도 해당 이벤트에 따른 콜백이 정상적으로 호출되지 않습니다.

혹시 제가 빠뜨린 부분이 있거나, 추가로 작성해야 할 부분이 있다면 알려주시면 감사하겠습니다.

**Comment by SteaI** [comment]
WinEventHook 을 거는경우 후킹을 명시적으로 종료하기 전까진 Thread context 를 유지해야합니다.

**Comment by Plurdis** [comment]
확인했습니다. 쓰레드 유지할 수 있도록 대기 코드 추가했습니다.

감사합니다.
