### ISSUE TITLE
TimeCat.Core 빌드가 되지 않습니다.

### ISSUE THREAD

**Issue by Plurdis** [iodes/TimeCat#53]
Visual Studio 2019 + .NET Core 3.0 환경에서 빌드했을때 다음과 같은 오류가 발생합니다.

![image](https://user-images.githubusercontent.com/23194065/66715589-19b1bc80-ee00-11e9-999c-6e2f837ebaf7.png)

검색해봤지만 별다른 정보가 발견되지 않았습니다.

해결방법이 있을까요?

**Comment by SteaI** [comment]
Grpc는 [해당 이슈](https://github.com/grpc/grpc/issues/17995)가 해결되지 않아서 사용자 계정은 무조건 ASCII 문자여야 합니다.

**Comment by Plurdis** [comment]
확인했습니다. 영문으로 새로운 사용자를 만들어 빌드했을때 성공적으로 빌드되는 것을 확인했습니다.
