### ISSUE TITLE
timing 동작 세부사항에 대한 질문입니다.

### ISSUE THREAD

**Issue by khg0712** [iodes/TimeCat#54]
![image](https://user-images.githubusercontent.com/25566139/66746989-59d77480-eebe-11e9-8f59-01c191d5b3f2.png)

사진 내 좌측 프로젝트 리스트내에서 시간이 표시되지 않는 프로젝트가 있는데 이 경우는 프로젝트내에 아무런 프로그램도 지정되지 않은 경우라서 그런 건가요?

**Comment by LiteHell** [comment]
그것도 일리가 있지만, 그 분류로 지정된 프로그램을 쓰지 않아서일 수도 있지 않을까요?

**Comment by khg0712** [comment]
@LiteHell 오 그렇네요. 정리하면 해당 분류로 지정된 프로그램의 사용시간이 0일때 저렇게 표시된다는 거겠죠?

**Comment by LiteHell** [comment]
@khg0712 네, 재가 맥을 안 써서 정확히 말씀드릴 수는 없지만, 제 생각엔 그럴 것 같습니다. 😄
