### ISSUE TITLE
TimeCat.Client 빌드 output  경로

### ISSUE THREAD

**Issue by SteaI** [iodes/TimeCat#65]
@Web-Engine 

~/TimeCat/Build/{Platforms}/TimeCat.ui.exe

Platforms: Windows, Unix, Linux, ...

경로에 출력 되도록 변경해주세요

**Comment by Web-Engine** [comment]
#66 에서 처리했습니다.
하지만, electron-builder에서 Windows, Unix, Linux가 아닌 win, mac, linux 형태의 os 매크로를 제공하여, 해당 형태로 수정하였습니다.
